package com.example.common

const val CATEGORIES = "Categories"
const val EXPENSES = "Expenses"
const val INCOMES = "Incomes"
const val BANK = "Bank"
const val BANK_PLUS = "plus"
const val BANK_MINUS = "minus"
const val TRANSACTION_TYPE = "type"
const val MONEY_TYPE = "money type"
const val ERROR = "error"
const val TAG = "myname"
const val TRANSACTIONS = "Transactions"
const val CASH = "наличные деньги"
const val CARD = "оплата картой"
const val CURRENCY = "currency"
const val USERS = "Users"
const val PARTNER_UID = "partner uid"
const val ID = "ID"
const val INCOMES_TITLE = "Обмен валюты"

const val DATE = "date"
const val CATEGORY = "category"
const val VALUE = "value"
const val UID = "uid"
const val ICON = "icon"
const val COLOR = "color"
const val BACKGROUND_COLOR = "backgroundColor"
const val NAME_BACKGROUND_COLOR = "nameBackgroundColor"
const val IS_MAIN_SOURCE = "mainSource"

const val BYN = "BYN"
const val USD = "USD"
const val EUR = "EUR"
const val RUB = "RUB"

const val NEW_SMS = "sms"

const val FULL_DATE = "dd.MM.yyyy"

const val BASE_CURRENCY_URL = "https://www.nbrb.by/api/exrates/"

const val VERSION = "Version"
const val URL = "url"
const val DESCRIPTION = "description"

const val WALLETS = "Wallets"
const val TRANSFERS = "Transfers"
const val SOURCE_ID = "sourceId"
const val TARGET_ID = "targetId"
const val NAME = "name"